name: CI testing build

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
  pull_request:
    branches:
      - '**'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run npm install
      run: npm install
    - name: Run webpack prod build
      run: npm run build
    - name: Upload prod bundle
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Prod Build
        path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.7
        with:
          name: Prod Build
          path: dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: MatteoGheza/conteggioore:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
